export const GET_ALL = "GET_ALL";
export const GET_BYID= "GET_BYID";
export const SEARCH_COUNTRY = "SEARCH_COUNTRY";
export const CREATE_ACTIVITY= "CREATE_ACTIVITY";
export const FILTER_CONTINENT= "FILTER_CONTINENT";
export const FILTER_ACTIVITY= "FILTER_ACTIVITY";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
export const ORDER_ALPHABETICALLY = "ORDER_ALPHABETICALLY";
